### ISSUE TITLE
Launcher won't start because of System.InvalidCastException

### ISSUE THREAD

**Issue by maddindeiss** [s4enhancededition/s4enhancededition#1]
Hi,
the launcher won't start on my PC. I checked the Windows EventLog and got the following error:

> Application: The Settlers IV Enhanced Edition.exe
CoreCLR Version: 5.0.521.16609
.NET Version: 5.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.
   at S4EE.AppWindow.Installationscheck() in C:\Users\kevin\source\repos\s4enhancededition\s4enhancededition\The Settlers IV Enhanced Edition\AppWindow.xaml.cs:line 131
   at S4EE.AppWindow..ctor() in C:\Users\kevin\source\repos\s4enhancededition\s4enhancededition\The Settlers IV Enhanced Edition\AppWindow.xaml.cs:line 44
   at S4EE.App.App_Startup(Object sender, StartupEventArgs e) in C:\Users\kevin\source\repos\s4enhancededition\s4enhancededition\The Settlers IV Enhanced Edition\App.xaml.cs:line 70
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at S4EE.App.Main()

It looks like, that there is a problem by getting the language value from the registry in `AppWindow.xaml.cs`.
The language is type `DWORD` in my registry and I think this will give you an `int` when you use `Registry.GetValue()`. 
Trying to cast an `int` to a `string` will produce the InvalidCastException.

I am not sure if there is something wrong with my registry entries and my problem does not occur on others setups?

**Comment by baflo** [comment]
+1

**Comment by baflo** [comment]
I'm gettting the same error for EE v1.1.9 and v1.1.8

**Comment by baflo** [comment]
Solved the problem. Apparently, the Enhanced Edition *requires* the History Edition to be installed and started at least once. It uses resources of the History Edition and without them it cannot start.

**Comment by LosWolfos** [comment]
got the same problem, only having the gold Edition from Gog.

**Comment by TheSettlersIVEnhancedEdition** [comment]
> got the same problem, only having the gold Edition from Gog.
> 
> Edit: Deleting the key and adding it as a Reg_DWORD again solved it for me.

Mark as Solved: Deleting the key and adding it as a Reg_DWORD again solved it for me.
